sampsite/music/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),
   # url(r'^songs/$', views.SongsView.as_view(), name='songs_index'),

    #Ingreso
   # url(r'^login_user/$', views.login_user, name='login_user'),


    #Registro
    url(r'^CreateAccount/$', views.UserformView.as_view(), name='CreateAccount'),

    # music/71/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),name='detail'),

  #  url(r'^(?P<pk>[0-9]+)/songs/$', views.DetailViewSongs.as_view(),name='detail_song'),
    # url(r'^(?P<pk>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),

    #/music/album/add/
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'^album/details/add$', views.SongCreate.as_view(), name='song-add'),
    # /music/album/2/
    url(r'^album/add/$', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/2/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

sampsite/sampsite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sampsite/music/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})
    def __str__(self):
        return  self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.pk})
    def __str__(self):
        return  self.song_title

sampsite/music/forms.py
from django.contrib.auth.models import User
from django import forms

class Userform(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

sampsite/music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Album, Song
from .forms import Userform

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

'''
class SongsView(generic.ListView):
    template_name = 'music/songs_index.html'
    def get_queryset(self):
        return Song.objects.all()
'''

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'
'''
class DetailViewSongs(generic.DetailView):
    model = Song
    template_name = 'music/details.html'
'''
class AlbumCreate(CreateView):
    model=Album
    fields =['artist', 'album_title', 'genre', 'album_logo']

class SongCreate(CreateView):
    model=Song
    fields =['file_type', 'song_title']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    succes_url = reverse_lazy('index')

def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})

class UserformView(View):
    form_class = Userform
    template_name = 'music/registration_form.html'
    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form' : form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            #Creates user but does not save it
            user = form.save(commit=False)

            #Clenaed (normalized) data
            username = form.cleaned_data['username']
            passworld = form.cleaned_data['passworld']
            user.ser_password(passworld)
            user.save()

            # Return user objects if credentials are correct
            user = authenticate(username=username, passworld=passworld)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form' : form})

sampsite/music/templates/music/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PythonMusic</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle=".navbar-collapse" data-target="topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:list' %}">PythonMusic</a>
        </div>
        <!--Items -->
        <div class="collapse navbar-collapse"id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:list' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:list' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp Song
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                   <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default"> Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp Song
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block  body %}

{% endblock %}
</body>
</html>

sampsite/music/templates/music/album_form.html
 {% extends 'music/base.html' %}
 {% block title %} Add New Album {% endblock %}
 {% block album_active %} active {% endblock %}

 {% block body %}
 <div class="container-fluid">
     <div class="row">
         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add new Album</h3>
                {% if error_message %}
                    <p><strong> {{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token%}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
         </div>
     </div>
 </div>
 </div>
 {% endblock %}

sampsite/music/templates/music/base.html
    <title>PythonMusic</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle=".navbar-collapse" data-target="topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">PythonMusic</a>
        </div>
        <!--Items -->
        <div class="collapse navbar-collapse"id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp Song
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                   <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default"> Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block  body %}

{% endblock %}

sampsite/music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:song-add' %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio Type</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <label>
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; {{ song.file_type }}
                                        </label>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

sampsite/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"> {{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2"> {{ field.label_tag }}</label>
        <div class="col-sm-10">
        {{ field }}
        </div>
    </div>
{% endfor %}

sampsite/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
{% extends 'music/base.html' %}
{% block  body %}

    <h1>ALBUMES
    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>
    </h1>

    <p><font size="4">¡Aquí encontraras los mejores albumen!</font></p>

    <ul>
        {% for album in object_list %}
        <li style="font-size:25px"><a href = "{% url 'music:detail' album.id %}"> {{ album.album_title }}</a><button class="btn btn-primary btn-lg" type="submit"> Editar</button><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><button type="button" class="btn btn-danger">Eliminar</button><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></li>

        {% endfor %}
   </ul>
<div id="OverviewText4">
  <img style="display:block;margin-left:320px" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNLb3ZSMbUWzxND9q221N3gBtvSKVDi_Rpx7gZlD51OACPP7my" />
</div>
{% endblock %}

</body>
</html>

sampsite/music/templates/music/registration_form.html
 {% extends 'music/base.html' %}
 {% block title %} Create Account{% endblock %}
 {% block album_active %} active {% endblock %}

 {% block body %}
 <div class="container-fluid">
     <div class="row">
         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add new Account</h3>
                {% if error_message %}
                    <p><strong> {{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token%}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
         </div>
     </div>
 </div>
 </div>
 {% endblock %}

sampsite/music/templates/music/song_form.html
 {% extends 'music/base.html' %}
 {% block title %} Add New Song {% endblock %}
 {% block album_active %} active {% endblock %}

 {% block body %}
 <div class="container-fluid">
     <div class="row">
         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
            <div class="panel-body">
                <h3>Add new Song</h3>
                {% if error_message %}
                    <p><strong> {{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token%}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
         </div>
     </div>
 </div>
 </div>
 {% endblock %}